//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cellar
    {
        public long IdCellar { get; set; }
        public long IDProducto { get; set; }
        public long IDFactura { get; set; }
        public Nullable<int> PorMayor { get; set; }
        public Nullable<int> PorMenor { get; set; }
        public Nullable<decimal> PrPorMayor { get; set; }
        public Nullable<decimal> PrPorMenor { get; set; }
        public Nullable<int> SalePorMayor { get; set; }
        public Nullable<int> SalePorMenor { get; set; }
        public Nullable<long> IdPorMayorMedida { get; set; }
        public Nullable<long> IdPorMenorMedida { get; set; }
        public Nullable<bool> Sate { get; set; }
        public Nullable<decimal> PVentaMayor { get; set; }
        public Nullable<decimal> PVentaMenor { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
