//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credito
    {
        public long IDCredito { get; set; }
        public Nullable<long> IDFactura { get; set; }
        public Nullable<long> IDUsaurio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Abona { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public string Abonador { get; set; }
        public string Estado { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
