//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public long IDDevolucion { get; set; }
        public long IDProducto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Unidad { get; set; }
        public long IDFactura { get; set; }
        public Nullable<long> IDMedida { get; set; }
        public Nullable<long> IDKardex { get; set; }
    }
}
