//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public long IDFacturaDetalle { get; set; }
        public Nullable<long> IDProducto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Unidades { get; set; }
        public Nullable<long> IDFactura { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<long> IdMedidaMetrica { get; set; }
        public Nullable<long> IDKardex { get; set; }
        public Nullable<int> Iva { get; set; }
        public Nullable<decimal> FleteAplicado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Siclo { get; set; }
        public Nullable<int> EnAlmacen { get; set; }
        public Nullable<int> EnBodega { get; set; }
        public Nullable<int> EnDevolucion { get; set; }
        public string Movimiento { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual MedidaMetrica MedidaMetrica { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
