//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KardexBodega
    {
        public long IDKardexBodega { get; set; }
        public Nullable<long> IDProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> ManoDeObra { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Entra { get; set; }
        public Nullable<int> Sale { get; set; }
        public string Movimiento { get; set; }
        public Nullable<long> IDUsuario { get; set; }
        public Nullable<System.DateTime> FechaSystema { get; set; }
    }
}
