//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public long IDKardex { get; set; }
        public Nullable<long> IDProducto { get; set; }
        public Nullable<int> ProductoEntra { get; set; }
        public Nullable<decimal> ProductoEntraPrecio { get; set; }
        public Nullable<int> ProductoSale { get; set; }
        public Nullable<decimal> ProductoSalePrecio { get; set; }
        public string IDFactura { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<int> Equivalencia { get; set; }
        public Nullable<long> Referencia { get; set; }
        public string Siclo { get; set; }
        public Nullable<long> IdMedidaMetrica { get; set; }
        public Nullable<int> Residuo { get; set; }
        public string Movimiento { get; set; }
        public Nullable<decimal> PrecioReal { get; set; }
        public Nullable<long> IDKardexBodega { get; set; }
        public Nullable<long> IDUbicacion { get; set; }
        public Nullable<long> FacturaDevolucion { get; set; }
        public Nullable<decimal> Flete { get; set; }
    
        public virtual MedidaMetrica MedidaMetrica { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
