//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        public long IDModulo { get; set; }
        public string Nombre { get; set; }
        public string Comando { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<bool> IsMDI { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Color { get; set; }
    }
}
