//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public long Station { get; set; }
        public Nullable<int> NumFactura { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public byte[] Foto { get; set; }
    }
}
