//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Cellar = new HashSet<Cellar>();
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
            this.Kardex = new HashSet<Kardex>();
            this.Traslados = new HashSet<Traslados>();
        }
    
        public long IDProducto { get; set; }
        public string Nombre { get; set; }
        public string CodBarra { get; set; }
        public Nullable<bool> Iva { get; set; }
        public Nullable<decimal> PVenta1 { get; set; }
        public Nullable<decimal> PVenta2 { get; set; }
        public Nullable<decimal> PVenta3 { get; set; }
        public Nullable<decimal> PVenta4 { get; set; }
        public Nullable<int> Equivalencia1 { get; set; }
        public Nullable<int> Equivalencia2 { get; set; }
        public Nullable<int> Equivalencia3 { get; set; }
        public Nullable<bool> StateMedida2 { get; set; }
        public Nullable<bool> StateMedida3 { get; set; }
        public Nullable<long> IDMedidaMetrica { get; set; }
        public Nullable<System.DateTime> FechaUltimaVenta { get; set; }
        public Nullable<System.DateTime> FechaUltimaCompra { get; set; }
        public Nullable<long> IDUltimaVenta { get; set; }
        public Nullable<long> IDUtimaCompra { get; set; }
        public Nullable<decimal> PCAnterior { get; set; }
        public Nullable<decimal> PVAnterior1 { get; set; }
        public Nullable<decimal> PVAnterior2 { get; set; }
        public Nullable<decimal> PVAnterior3 { get; set; }
        public string NombreAnterior { get; set; }
        public string CodRapido { get; set; }
        public Nullable<int> ExistenciaMinima { get; set; }
        public Nullable<long> IDMarca { get; set; }
        public Nullable<long> IDGrupo { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> EdPVenta1 { get; set; }
        public Nullable<bool> EdPVenta2 { get; set; }
        public Nullable<bool> EdPVenta3 { get; set; }
        public Nullable<int> ExistenciaActual { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<long> IDUsuario { get; set; }
        public byte[] FotoProducto { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public Nullable<long> IDUbicacion { get; set; }
        public Nullable<int> EnBodega { get; set; }
        public Nullable<bool> Notificar { get; set; }
        public Nullable<bool> EdNombre { get; set; }
        public Nullable<bool> MostraNotificar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cellar> Cellar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual Grupo Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual MedidaMetrica MedidaMetrica { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traslados> Traslados { get; set; }
    }
}
