//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public long IDReservacion { get; set; }
        public long IDProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public bool AplicaIva { get; set; }
        public long IDCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<long> IDUsuario { get; set; }
        public string Comentario { get; set; }
        public Nullable<long> IDMedida { get; set; }
    }
}
