//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslados
    {
        public long IDTraslado { get; set; }
        public Nullable<long> IDProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string TrasladoDe { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<long> IDUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
