//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaKardex
    {
        public long IDKardex { get; set; }
        public Nullable<long> IDProducto { get; set; }
        public string Producto { get; set; }
        public Nullable<int> ProductoEntra { get; set; }
        public Nullable<decimal> ProductoEntraPrecio { get; set; }
        public Nullable<int> ProductoSale { get; set; }
        public Nullable<decimal> ProductoSalePrecio { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public string Medida { get; set; }
        public Nullable<decimal> PrecioReal { get; set; }
        public string Siclo { get; set; }
    }
}
