//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaVenta
    {
        public long IDProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Salio { get; set; }
        public Nullable<decimal> Vendio { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
